/**
 * @name Premium
 * @version 0.1.5
 * @author Pi
 * @description become epic hacker and listen along without giving money to spotify
 * @website https://github.com/pipipear/BD
 * @source https://raw.githubusercontent.com/pipipear/BD/main/Plugins/Premium/Premium.plugin.js
 * @updateUrl https://raw.githubusercontent.com/pipipear/BD/main/Plugins/Premium/Premium.plugin.js
 */

class Premium {
	log(m) {
		console.log(
			`%c[%cPremium%c] %c${m}`,
			'font-weight: bold; color: #118239',
			'font-weight: bold; color: #1ED760',
			'font-weight: bold; color: #118239', ''
		);
	}

	load() {
		if (window.realPremiumFunctions) {
			this.log('global reference already exists');
		} else {
			window.realPremiumFunctions = {
				README: 'this key-value array holds the original spotify premium check functions, it was automatically generated by the Premium plugin',
				ensureSpotifyPremium: BdApi.findModuleByProps('ensureSpotifyPremium').ensureSpotifyPremium,
				isSpotifyPremium: BdApi.findModuleByProps('isSpotifyPremium').isSpotifyPremium
			}
			this.log('created new global reference');
		}
	}

	start() {
		BdApi.findModuleByProps('ensureSpotifyPremium').ensureSpotifyPremium = () => {
			this.log('ensureSpotifyPremium bypassed');
			return Promise.resolve();
		}
		BdApi.findModuleByProps('isSpotifyPremium').isSpotifyPremium = () => {
			this.log('isSpotifyPremium bypassed');
			return true
		}
		this.log('patched premium checks');
	}
	
	stop() {
		BdApi.findModuleByProps('ensureSpotifyPremium').ensureSpotifyPremium = window.realPremiumFunctions.ensureSpotifyPremium;
		BdApi.findModuleByProps('isSpotifyPremium').isSpotifyPremium = window.realPremiumFunctions.isSpotifyPremium;
		this.log('unpatched premium checks');
	}
}
